[package]
name = "tauri-app"
version.workspace = true
description = "Tauri + Leptos SSR demo"
edition.workspace = true
rust-version.workspace = true
publish.workspace = true

[lib]
name = "tauri_app_lib"
crate-type = ["staticlib", "cdylib", "rlib"]

[build-dependencies]
tauri-build.workspace = true

[dependencies]
app = { workspace = true, features = ["ssr"] }
tauri.workspace = true
tauri-plugin-leptos-ssr.workspace = true
tauri-plugin-log.workspace = true
log.workspace = true

[dev-dependencies]
serde_json.workspace = true
toml.workspace = true
